"""Constants for Granola application."""

# Window dimensions
WINDOW_MIN_WIDTH = 1000
WINDOW_MIN_HEIGHT = 600

# Panel dimensions (3-column layout)
LEFT_PANEL_WIDTH = 200
RIGHT_PANEL_WIDTH = 300
SPLITTER_DEFAULT_SIZES = [LEFT_PANEL_WIDTH, 500, RIGHT_PANEL_WIDTH]

# Layout
LAYOUT_SPACING = 15
LAYOUT_MARGIN = 20
LAYOUT_MARGIN_SMALL = 10

# Audio
DEFAULT_SAMPLE_RATE = 48000
AUDIO_CHUNK_SIZE = 4096
TIMER_INTERVAL_MS = 100

# Storage
MIN_DISK_SPACE_BYTES = 500 * 1024 * 1024  # 500 MB

# Notes
NOTES_AUTO_SAVE_INTERVAL_MS = 30000  # 30 seconds

# File Search
FILE_SEARCH_DELAY_MS = 5 * 60 * 1000  # 5 minutes before sync
FILE_SEARCH_POLL_INTERVAL_MS = 60 * 1000  # Check every minute
MIN_SYNC_DURATION_SECONDS = 30  # Skip recordings shorter than 30s
CHAT_MAX_HISTORY = 50  # Max messages to retrieve
